import type { LandingContent } from "@/components/ServiceLanding";

export const servicePages: Record<string, LandingContent> = {
  "bulk-billing-physiotherapy-newcastle": {
    slug: "bulk-billing-physiotherapy-newcastle",
    eyebrow: "Bulk Billing Physiotherapy Newcastle",
    h1: "Bulk Billing Physiotherapy in Newcastle",
    serviceName: "Bulk Billing Physiotherapy Newcastle",
    intro: "Bulk-billed physiotherapy in Newcastle and Lake Macquarie through a GP Care Plan — expert, hands-on treatment with no out-of-pocket cost.",
    lead: [
      "Did you know your physiotherapy could be completely bulk billed? At Therapy 4 All, patients referred by their GP under a Chronic Disease Management (CDM/EPC) plan receive expert physiotherapy with no out-of-pocket cost — at our clinics in Mount Hutton, Warners Bay, Wallsend and Rutherford.",
      "A GP Care Plan (also called an Enhanced Primary Care or EPC plan) is designed for people managing an ongoing or chronic condition. If you qualify, Medicare covers up to five allied health visits per year, and we bulk bill those visits so you pay nothing.",
      "It's the same thorough, hands-on care as any of our appointments — just funded through Medicare.",
    ],
    sections: [
      { h2: "What is a GP Care Plan?", body: ["A GP Care Plan is a Medicare initiative that helps people with chronic or complex conditions access allied health services like physiotherapy. Your GP assesses whether you're eligible and, if so, provides a referral for up to five bulk-billed sessions per calendar year.", "Common conditions that may qualify include arthritis, chronic back or neck pain, diabetes-related issues, and recovery from injury or surgery. Ask your GP whether a Care Plan is right for you."] },
      { h2: "What's included in a bulk-billed visit", body: ["Your bulk-billed physiotherapy is a full, hands-on appointment — there's no reduced service."],
        list: ["Review of your relevant medical history","Assessment of your current condition","Functional assessment based on your daily activities","Review of imaging and reports","Hands-on treatment (soft tissue work, joint mobilisation)","An individualised plan, education and home exercises"] },
      { h2: "How to get started", body: ["Getting started is simple: book an appointment with your GP and ask whether you're eligible for a Chronic Disease Management (Care Plan). If you are, they'll provide a referral. Bring it to your first appointment with us and we'll bulk bill your treatment.", "No referral yet? You're still welcome to book a standard consultation directly — and we can guide you on whether a Care Plan may suit you."] },
    ],
    faqs: [
      { q: "Does bulk billing mean it's free?", a: "Yes — with a valid GP Care Plan referral, Medicare covers the cost and we bulk bill, so there's no out-of-pocket cost to you for those sessions." },
      { q: "How many bulk-billed sessions can I have?", a: "Medicare covers up to five allied health visits per calendar year under a Chronic Disease Management plan, shared across all allied health services." },
      { q: "How do I get a GP Care Plan?", a: "See your GP and ask whether you're eligible for a Chronic Disease Management (CDM/EPC) plan. If so, they'll write a referral you can bring to us." },
    ],
    related: [
      { label: "Musculoskeletal Physiotherapy Newcastle", href: "/musculoskeletal-physiotherapy-newcastle" },
      { label: "Chronic Pain Physiotherapy Newcastle", href: "/chronic-pain-physiotherapy-newcastle" },
      { label: "Aged Care Physiotherapy Newcastle", href: "/aged-care-physiotherapy-newcastle" },
    ],
    ctaTitle: "Book your bulk-billed physiotherapy today",
  },
  "sports-physiotherapy-newcastle": {
    slug: "sports-physiotherapy-newcastle",
    eyebrow: "Sports Physiotherapy Newcastle",
    h1: "Sports Physiotherapy in Newcastle",
    serviceName: "Sports Physiotherapy Newcastle",
    intro: "Expert sports physiotherapy in Newcastle and Lake Macquarie — hands-on treatment and rehabilitation to recover from injury, restore movement and prevent recurrence.",
    lead: [
      "Whether you're a weekend runner, a competitive athlete or someone who's picked up a niggling injury, Therapy 4 All's sports physiotherapists help you recover quickly and safely — and get back to the activity you love.",
      "Our team combines skilled manual therapy with targeted, progressive exercise, so you don't just settle the pain — you rebuild strength and address the cause to stop it coming back.",
      "We treat sports and overuse injuries across our Mount Hutton, Warners Bay, Wallsend and Rutherford clinics, including our fully equipped rehabilitation gym at Mount Hutton.",
    ],
    sections: [
      { h2: "Sports injuries we treat", body: ["We assess and treat a wide range of sports and overuse injuries, tailoring your rehabilitation to your sport, goals and season."],
        list: ["Sprains, strains and muscle tears","Knee, ankle and shoulder injuries","Tendon and overuse injuries","Back and neck pain from sport","Post-surgical sports rehabilitation","Return-to-sport programs"] },
      { h2: "Our approach", body: ["Every program starts with a thorough assessment to understand exactly what's driving your injury. From there we combine hands-on treatment — such as manual therapy and dry needling — with a progressive, sport-specific exercise plan.", "Our Mount Hutton hub has a fully equipped gym, so we can guide strength and conditioning work under supervision and confidently progress you back to full activity."] },
      { h2: "Preventing re-injury", body: ["Recovering from a sports injury isn't just about getting out of pain — it's about coming back stronger and reducing the risk of it happening again. We build strength, control and movement quality so you return to sport with confidence."] },
    ],
    faqs: [
      { q: "Do I need a referral for sports physiotherapy?", a: "No — you can book directly. A GP referral is only needed if you want to be treated under a bulk-billed Care Plan." },
      { q: "Do you use dry needling?", a: "Yes. Our physiotherapists use dry needling, manual therapy and targeted exercise as part of tailored sports rehabilitation where appropriate." },
      { q: "Can you help me return to my sport?", a: "Absolutely. We build sport-specific return-to-play programs, using our Mount Hutton gym to progress strength and confidence safely." },
    ],
    related: [
      { label: "Musculoskeletal Physiotherapy Newcastle", href: "/musculoskeletal-physiotherapy-newcastle" },
      { label: "Post-Operative Rehabilitation Newcastle", href: "/post-operative-rehabilitation-newcastle" },
      { label: "Bulk Billing Physiotherapy Newcastle", href: "/bulk-billing-physiotherapy-newcastle" },
    ],
    ctaTitle: "Recover from your sports injury with us",
  },
  "womens-health-physiotherapy-newcastle": {
    slug: "womens-health-physiotherapy-newcastle",
    eyebrow: "Women's Health Physiotherapy Newcastle",
    h1: "Women's Health Physiotherapy in Newcastle",
    serviceName: "Women's Health Physiotherapy Newcastle",
    intro: "Compassionate women's health physiotherapy in Newcastle and Lake Macquarie, with a female physiotherapist — evidence-based, individualised care to improve your health, confidence and quality of life.",
    lead: [
      "At Therapy 4 All, our women's health physiotherapy is led by Prakriti, a compassionate physiotherapist passionate about helping women improve their health, confidence and quality of life.",
      "We understand that women's health concerns can be sensitive, which is why many patients value having a female physiotherapist. Prakriti provides evidence-based, individualised care in a supportive, respectful setting.",
      "Whether you're navigating pregnancy or the postnatal period, recovering after surgery, or managing an ongoing concern, we build a personalised program designed around you.",
    ],
    sections: [
      { h2: "How women's health physiotherapy helps", body: ["Women's health physiotherapy supports you through many stages of life with practical, personalised care."],
        list: ["Pregnancy and postnatal recovery","Pelvic health and core strength","Strength and core rehabilitation","Post-operative rehabilitation","Musculoskeletal pain and posture","Building confidence and long-term wellbeing"] },
      { h2: "A comfortable, supportive approach", body: ["We know that seeking help for women's health concerns takes trust. Prakriti creates a welcoming, respectful environment and takes the time to understand your goals, so your care always feels comfortable and individualised.", "Every program is evidence-based and tailored to your body and your life — practical, goal-oriented and sustainable."] },
      { h2: "Strength and core rehabilitation", body: ["Building deep core strength, stability and control is central to women's health. Under physiotherapy guidance — including in our fully equipped Mount Hutton gym — we tailor an exercise-based program to your needs and progress it safely over time."] },
    ],
    faqs: [
      { q: "Can I see a female physiotherapist?", a: "Yes. Our women's health physiotherapy is provided by Prakriti, a female physiotherapist — many patients appreciate this for sensitive concerns." },
      { q: "Do I need a referral for women's health physiotherapy?", a: "No — you can book directly. A GP referral is only required for bulk-billed Care Plan treatment." },
      { q: "What can women's health physiotherapy help with?", a: "It supports pregnancy and postnatal recovery, pelvic health, core strength, post-operative rehabilitation and musculoskeletal concerns — with care tailored to you." },
    ],
    related: [
      { label: "Chronic Pain Physiotherapy Newcastle", href: "/chronic-pain-physiotherapy-newcastle" },
      { label: "Post-Operative Rehabilitation Newcastle", href: "/post-operative-rehabilitation-newcastle" },
      { label: "Bulk Billing Physiotherapy Newcastle", href: "/bulk-billing-physiotherapy-newcastle" },
    ],
    ctaTitle: "Book women's health physiotherapy today",
  },
  "chronic-pain-physiotherapy-newcastle": {
    slug: "chronic-pain-physiotherapy-newcastle",
    eyebrow: "Chronic Pain Physiotherapy Newcastle",
    h1: "Chronic Pain Physiotherapy in Newcastle",
    serviceName: "Chronic Pain Physiotherapy Newcastle",
    intro: "Chronic pain physiotherapy in Newcastle led by a Master's-qualified pain physiotherapist — evidence-based care that reduces fear of movement and helps you return to what matters.",
    lead: [
      "Persistent pain is complex, and it affects far more than the body. At Therapy 4 All, our chronic pain physiotherapy is led by Daniel, who holds a Master's degree in Pain Management from the University of Sydney.",
      "Our approach combines modern pain science with hands-on treatment and simple, practical strategies — helping you move with confidence and reduce the fear that so often keeps pain cycles going.",
      "We focus on long-term outcomes rather than quick fixes, helping you return to the activities, work and relationships that matter most.",
    ],
    sections: [
      { h2: "Understanding persistent pain", body: ["Chronic pain is pain that continues beyond normal healing time. It's influenced by many factors — not just tissue damage — which is why an active, evidence-based approach works far better than rest alone.", "We take the time to understand your individual pain experience and build a plan that gradually rebuilds your capacity and confidence to move."] },
      { h2: "How we help", body: ["Your program is tailored to you and progressed at a pace that feels safe."],
        list: ["Understanding your pain and its drivers","Graded movement to reduce fear","Hands-on treatment where helpful","Practical day-to-day strategies","Strength and conditioning","A graded return to meaningful activities"] },
      { h2: "Expert, personalised care", body: ["With a Master's degree in Pain Management, Daniel brings advanced expertise to complex and persistent pain. Whether you're managing long-standing back pain, widespread pain, or pain that lingers after an injury, we help you take back control of your movement and life."] },
    ],
    faqs: [
      { q: "Can physiotherapy help chronic pain?", a: "Yes. An active, evidence-based physiotherapy approach is one of the most effective ways to manage chronic pain — restoring movement, reducing fear and improving function." },
      { q: "Who leads chronic pain care at Therapy 4 All?", a: "Daniel, who holds a Master's degree in Pain Management from the University of Sydney, leads our chronic pain physiotherapy." },
      { q: "Is chronic pain physiotherapy bulk billed?", a: "It can be, with a GP Care Plan referral for eligible patients. Otherwise a standard consultation is $90." },
    ],
    related: [
      { label: "Musculoskeletal Physiotherapy Newcastle", href: "/musculoskeletal-physiotherapy-newcastle" },
      { label: "Bulk Billing Physiotherapy Newcastle", href: "/bulk-billing-physiotherapy-newcastle" },
      { label: "Aged Care Physiotherapy Newcastle", href: "/aged-care-physiotherapy-newcastle" },
    ],
    ctaTitle: "Take the first step toward moving with confidence",
  },
  "post-operative-rehabilitation-newcastle": {
    slug: "post-operative-rehabilitation-newcastle",
    eyebrow: "Post-Operative Rehabilitation Newcastle",
    h1: "Post-Operative Rehabilitation in Newcastle",
    serviceName: "Post-Operative Rehabilitation Newcastle",
    intro: "Post-operative physiotherapy in Newcastle and Lake Macquarie — structured rehabilitation to rebuild strength, movement and confidence after surgery.",
    lead: [
      "The success of your surgery depends heavily on the rehabilitation that follows. At Therapy 4 All, we provide structured, hands-on post-operative physiotherapy to help you recover safely and return to daily life.",
      "Whether you've had a joint replacement, a knee or shoulder reconstruction, spinal surgery or another procedure, we tailor your program to your surgeon's guidelines and your goals — and progress it as you heal.",
      "Our fully equipped Mount Hutton rehabilitation gym is ideal for supervised strength and conditioning as you get stronger.",
    ],
    sections: [
      { h2: "Why rehabilitation matters", body: ["After surgery, muscles weaken and joints stiffen quickly. Well-planned physiotherapy restores movement early, rebuilds strength, and reduces the risk of complications and a stiff, poorly functioning result.", "We work within your surgeon's precautions at every stage, so your recovery is both safe and effective."] },
      { h2: "What your program includes", body: ["Your rehabilitation is graded and guided from your first appointment through to full recovery."],
        list: ["Restoring movement and range","Progressive strengthening","Swelling and pain management","Walking, balance and function","Supervised gym-based rehab at Mount Hutton","A safe, staged return to activity"] },
      { h2: "Recovering with confidence", body: ["Our goal is to get you back to the things you enjoy — work, sport, family and everyday life — as strongly and safely as possible. We keep you on track, motivated and progressing throughout your recovery."] },
    ],
    faqs: [
      { q: "When should I start rehab after surgery?", a: "Early, guided movement is usually important. Once you're home and cleared, contact us and we'll arrange an appointment within your surgeon's guidelines." },
      { q: "Do you rehab joint replacements?", a: "Yes — we provide structured rehabilitation after hip and knee replacements, shoulder and other surgeries, tailored to your recovery." },
      { q: "Can post-op rehab be bulk billed?", a: "It can be, with a GP Care Plan referral for eligible patients. Otherwise a standard consultation is $90." },
    ],
    related: [
      { label: "Sports Physiotherapy Newcastle", href: "/sports-physiotherapy-newcastle" },
      { label: "Musculoskeletal Physiotherapy Newcastle", href: "/musculoskeletal-physiotherapy-newcastle" },
      { label: "Bulk Billing Physiotherapy Newcastle", href: "/bulk-billing-physiotherapy-newcastle" },
    ],
    ctaTitle: "Recover strongly after your surgery",
  },
  "musculoskeletal-physiotherapy-newcastle": {
    slug: "musculoskeletal-physiotherapy-newcastle",
    eyebrow: "Musculoskeletal Physiotherapy Newcastle",
    h1: "Musculoskeletal Physiotherapy in Newcastle",
    serviceName: "Musculoskeletal Physiotherapy Newcastle",
    intro: "Musculoskeletal physiotherapy in Newcastle and Lake Macquarie — expert assessment and hands-on treatment for back, neck, joint and muscle pain.",
    lead: [
      "Musculoskeletal (MSK) physiotherapy is the core of what we do at Therapy 4 All — assessing and treating pain and injuries of the muscles, joints, ligaments and nerves.",
      "From a stiff neck or sore back to a persistent shoulder or knee problem, our physiotherapists identify what's really driving your pain and treat both the symptoms and the cause.",
      "We combine hands-on treatment with practical, targeted exercise, so you get lasting relief and return to moving comfortably.",
    ],
    sections: [
      { h2: "Conditions we treat", body: ["We assess and treat a broad range of musculoskeletal conditions across all ages."],
        list: ["Back and neck pain","Shoulder, elbow and wrist pain","Hip, knee and ankle pain","Arthritis and joint pain","Muscle strains and ligament sprains","Postural and work-related pain"] },
      { h2: "Our hands-on approach", body: ["Every appointment begins with a thorough assessment. From there we use manual therapy, dry needling and joint mobilisation to ease pain and restore movement, alongside an individualised exercise program to build strength and prevent recurrence.", "We explain what's going on in plain language and give you practical strategies you can use between visits."] },
      { h2: "Lasting results", body: ["Our focus is on outcomes that last. Rather than just settling the pain, we address the underlying cause and build your strength and movement quality — so you stay comfortable and active for the long term."] },
    ],
    faqs: [
      { q: "Do I need a referral for musculoskeletal physiotherapy?", a: "No — you can book a standard consultation directly. A GP referral is only needed for bulk-billed Care Plan treatment." },
      { q: "What does a first appointment involve?", a: "A thorough assessment of your condition, hands-on treatment, and an individualised exercise and progression plan — a standard 30-minute consultation is $90." },
      { q: "Do you treat back and neck pain?", a: "Yes — back and neck pain are among the most common conditions we treat, with hands-on treatment and targeted exercise." },
    ],
    related: [
      { label: "Sports Physiotherapy Newcastle", href: "/sports-physiotherapy-newcastle" },
      { label: "Chronic Pain Physiotherapy Newcastle", href: "/chronic-pain-physiotherapy-newcastle" },
      { label: "Bulk Billing Physiotherapy Newcastle", href: "/bulk-billing-physiotherapy-newcastle" },
    ],
    ctaTitle: "Get relief from your pain — book today",
  },
  "workplace-physiotherapy-newcastle": {
    slug: "workplace-physiotherapy-newcastle",
    eyebrow: "Workplace Physiotherapy Newcastle",
    h1: "Workplace & Return to Work Physiotherapy in Newcastle",
    serviceName: "Workplace Physiotherapy Newcastle",
    intro: "Workplace and return-to-work physiotherapy in Newcastle and the Hunter — assessment, treatment and reporting to help injured workers recover and return safely.",
    lead: [
      "Therapy 4 All supports injured workers and employers across Newcastle and the Hunter with practical, results-driven workplace physiotherapy.",
      "We help workers recover from injury, manage pain, and return to work safely and confidently — with clear assessment, treatment and communication throughout.",
      "We're experienced working alongside employers, GPs and case managers, and provide the reporting needed to support a smooth return-to-work process.",
    ],
    sections: [
      { h2: "How we support injured workers", body: ["Our workplace physiotherapy focuses on getting you back to full, safe function."],
        list: ["Assessment of your work injury","Hands-on treatment and pain management","Progressive, functional rehabilitation","Return-to-work planning","Clear communication and reporting","Advice on safe work and prevention"] },
      { h2: "Working with employers and case managers", body: ["We understand that a good return-to-work outcome depends on clear communication between everyone involved. We keep workers, employers, GPs and case managers informed, and provide reliable, timely reporting.", "Our goal is a safe, sustainable return to work that supports both the worker and the workplace."] },
      { h2: "Prevention and long-term function", body: ["Beyond treating the injury, we focus on building the strength, movement and confidence needed to work safely long term — reducing the risk of re-injury."] },
    ],
    faqs: [
      { q: "Do you treat workers compensation injuries?", a: "Yes. We support injured workers with assessment, treatment, return-to-work planning and reporting, working alongside employers and case managers." },
      { q: "Do you provide reports?", a: "Yes — we provide clear, timely reporting to support the return-to-work process and keep everyone informed." },
      { q: "Which clinics offer workplace physiotherapy?", a: "Workplace and return-to-work physiotherapy is available across our Mount Hutton, Warners Bay, Wallsend and Rutherford clinics." },
    ],
    related: [
      { label: "Musculoskeletal Physiotherapy Newcastle", href: "/musculoskeletal-physiotherapy-newcastle" },
      { label: "Post-Operative Rehabilitation Newcastle", href: "/post-operative-rehabilitation-newcastle" },
      { label: "Chronic Pain Physiotherapy Newcastle", href: "/chronic-pain-physiotherapy-newcastle" },
    ],
    ctaTitle: "Support a safe return to work",
  },
  "aged-care-physiotherapy-newcastle": {
    slug: "aged-care-physiotherapy-newcastle",
    eyebrow: "Aged Care Physiotherapy Newcastle",
    h1: "Aged Care Physiotherapy in Newcastle",
    serviceName: "Aged Care Physiotherapy Newcastle",
    intro: "Aged care physiotherapy in Newcastle and Lake Macquarie — helping older adults improve mobility, balance and strength to stay active and independent.",
    lead: [
      "Therapy 4 All provides aged care physiotherapy to help older adults stay mobile, strong and independent. Our team is led by Keith, an experienced physiotherapist with a strong background in aged care and complex rehabilitation.",
      "Whether you're recovering from illness or a hospital stay, managing a long-term condition, or simply wanting to stay steady on your feet, we build gentle, effective programs tailored to you.",
      "Care is delivered across our clinics, including our fully equipped Mount Hutton rehabilitation gym — ideal for supervised strength and balance work.",
    ],
    sections: [
      { h2: "How we help older adults", body: ["Our aged care physiotherapy focuses on the things that keep you safe, capable and independent."],
        list: ["Improving mobility and walking","Balance training and falls prevention","Strength and conditioning","Recovery after illness or hospital","Managing arthritis and chronic conditions","Supporting confidence and independence"] },
      { h2: "Experienced, compassionate care", body: ["Keith brings extensive experience in aged care, complex rehabilitation and multidisciplinary care. His approach combines hands-on treatment with structured, practical rehabilitation designed around each person's needs and goals.", "We work closely with patients, families and care teams to improve mobility, reduce pain and support long-term function."] },
      { h2: "Falls prevention and strength", body: ["Falls are a leading cause of lost independence for older adults, and most are preventable. Our balance and strength programs — supported by the gym at Mount Hutton — help you stay steady, confident and active."] },
    ],
    faqs: [
      { q: "Do you help older adults with balance and falls?", a: "Yes. Balance training and falls prevention are a key part of our aged care physiotherapy, using strength and balance exercises to keep you steady." },
      { q: "Can aged care physiotherapy be bulk billed?", a: "It can be, with a GP Care Plan referral for eligible patients. Otherwise a standard consultation is $90." },
      { q: "Who leads aged care physiotherapy?", a: "Keith, an experienced physiotherapist with a strong background in aged care and complex rehabilitation, leads this area." },
    ],
    related: [
      { label: "Chronic Pain Physiotherapy Newcastle", href: "/chronic-pain-physiotherapy-newcastle" },
      { label: "Musculoskeletal Physiotherapy Newcastle", href: "/musculoskeletal-physiotherapy-newcastle" },
      { label: "Bulk Billing Physiotherapy Newcastle", href: "/bulk-billing-physiotherapy-newcastle" },
    ],
    ctaTitle: "Help stay mobile, strong and independent",
  },
};
